version: '3'

services:
  ## reverse-proxy: ## let s call it traefik!
  traefik:
    # The official v2 Traefik docker image
    ## image: traefik:v2.2
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  service:
    build: .
    environment:
      - MY_MESSAGE=load1
    labels:
      ## - 'traefik.frontend.rule=Host:whoami.docker.localhost'
      ## - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      ## - 'traefik.http.routers.whoami.rule=Host(`load.test`)'
      - 'traefik.frontend.rule=Host:load.test'
      - 'traefik.backend=load'
  service2:
    build: .
    environment:
      - MY_MESSAGE=load2
    labels:
      ## - 'traefik.frontend.rule=Host:whoami.docker.localhost'
      ## - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      ## - 'traefik.http.routers.whoami.rule=Host(`load.test`)'
      - 'traefik.frontend.rule=Host:load.test'
      - 'traefik.backend=load'

